#!/bin/sh

. ~/src/dwmblocks/modules/modules-common

info=$(bluetoothctl info)

if [ "$info" = "Missing device address argument" ]; then
    printf "$(color  red)"
else
	name=$(printf "$info" | sed -n '/Name/{s_\s*Name: \(.*\)_\1_;p}')
    printf "$(color  blue) $name"
fi
